trigger:
  - main

# variables:
#   AgentName: ''  # Variable to store agent name dynamically

# pool:
#   name: Default  # Using the Default agent pool

stages:
- stage: One
  jobs:
  - job: A
    pool:
      name: Default  # Ensures the same pool
    steps:
    - script: |
        echo "Running on agent: $AGENT_NAME"
        echo "##vso[task.setvariable variable=MyVar;isOutput=true]$AGENT_NAME"
      name: ProduceVar  # This is an important step name for referencing later
      # name: ProduceVar  # because we're going to depend on it, we need to name the step

- stage: Two
  dependsOn:
  - One
  jobs:
  - job: B
    pool:
      name: Default  # Ensures the same pool
    variables:
      # map the output variable from A into this job
      varFromA: $[ dependencies.One.A.outputs['ProduceVar.MyVar'] ]
    steps:
    - script: echo $(varFromA) # this step uses the mapped-in variable

- stage: Three
  dependsOn:
  - One
  - Two
  jobs:
  - job: C
    pool:
      name: Default  # Ensures the same pool
    variables:
      # map the output variable from A into this job
      varFromA: $[ dependencies.One.A.outputs['ProduceVar.MyVar'] ]
    steps:
    - script: echo $(varFromA) # this step uses the mapped-in variable