
trigger:
  - main

stages:
- stage: One
  jobs:
  - job: A
    pool:
      name: Linux-agent-pool
    steps:
    - script: |
        docker --version
        docker ps
        echo "Running on agent: $AGENT_NAME"
        echo "##vso[task.setvariable variable=MyVar;isOutput=true]$AGENT_NAME"
      name: ProduceVar

- stage: Two
  dependsOn:
    - One
  jobs:
  - job: B_waitForValidation
    pool: server  # Server job required for ManualValidation
    variables:
      varFromA: $[ dependencies.One.A.outputs['ProduceVar.MyVar'] ]
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440
      inputs:
        notifyUsers: |
          mohammedanuwarsadat@gmail.com
        instructions: 'Please validate the build configuration and resume'
        onTimeout: 'resume'

  - job: B_followUp
    dependsOn: B_waitForValidation
    pool:
      name: Linux-agent-pool
    variables:
      varFromA: $[ dependencies.One.A.outputs['ProduceVar.MyVar'] ]
    steps:
    - script: echo $(varFromA)

- stage: Three
  dependsOn:
    - One
    - Two
  jobs:
  - job: C_waitForValidation
    pool: server  # Server job required for ManualValidation
    variables:
      varFromA: $[ dependencies.One.A.outputs['ProduceVar.MyVar'] ]
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440
      inputs:
        notifyUsers: |
          mohammedanuwarsadat@gmail.com
        instructions: 'Please validate the build configuration and resume'
        onTimeout: 'resume'
  - job: C
    pool:
      name: Linux-agent-pool
    variables:
      varFromA: $[ dependencies.One.A.outputs['ProduceVar.MyVar'] ]
    steps:
    - script: echo $(varFromA)


